/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu_superadmin;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luthf
 */
public class Buku extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public Buku() {
        initComponents();
        loadTable();
    }
    
    private void cariin() {
        Object[]baris={"Kode Buku","Judul Buku","Tanggal Beli","Pengarang","Penerbit","Tahun Terbit","Jumlah Buku"};
        DefaultTableModel tablek = new DefaultTableModel(null, baris);
        tabledor.setModel(tablek);
        String carii = cari.getText();
        
        try{
            Statement state=handler_class.Koneksi.konek().createStatement();
            String sql = "select * from buku WHERE kode_buku LIKE '%"+carii+"%'OR judul_buku LIKE '"+carii+"'" ;
            ResultSet cari = state.executeQuery(sql);
            
            while (cari.next()){
            String a = cari.getString(1);
            String b = cari.getString(2);
            String c = cari.getString(3);
            String d = cari.getString(4);
            String e = cari.getString(5);
            String f = cari.getString(6);
            String g = cari.getString(7);
            Object[]data={a,b,c,d,e,f,g};
            tablek.addRow(data);
        }
    }catch (Exception e){
        System.out.println("Data Gak ada!");
    }
    }
    
    protected void loadTable() {
        Object[]baris={"Kode Buku","Judul Buku","Tanggal Beli","Pengarang","Penerbit","Tahun Terbit","Jumlah Buku"};
        DefaultTableModel tablek = new DefaultTableModel(null, baris);
        tabledor.setModel(tablek);
        
        try{
            Statement state=handler_class.Koneksi.konek().createStatement();
            String sql = "select * from buku ";
            ResultSet cari = state.executeQuery(sql);
            
            while (cari.next()){
            String a = cari.getString(1);
            String b = cari.getString(2);
            String c = cari.getString(3);
            String d = cari.getString(4);
            String e = cari.getString(5);
            String f = cari.getString(6);
            String g = cari.getString(7);
            Object[]data={a,b,c,d,e,f,g};
            tablek.addRow(data);
        }
    }catch (Exception e){
    }
    }
    
    private void kosong(){
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");     
        Date date = new Date();
        kode_buku.setText("Kode Buku");
        kode_buku.setForeground(new Color(153, 153, 153));
        judul_buku.setText("Judul Buku");
        judul_buku.setForeground(new Color(153, 153, 153));
        tanggal_beli.setDate(date);
        tanggal_beli.setForeground(new Color(0, 0, 0));
        pengarang.setText("Pengarang");
        pengarang.setForeground(new Color(153, 153, 153));
        penerbit.setText("Penerbit");
        penerbit.setForeground(new Color(153, 153, 153));
        tahun_terbit.setText("Tahun Terbit");
        tahun_terbit.setForeground(new Color(153, 153, 153));
        jumlah_buku.setText("Jumlah Buku");
        jumlah_buku.setForeground(new Color(153, 153, 153));
        cari.setText("");
        loadTable();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kode_buku = new javax.swing.JTextField();
        judul_buku = new javax.swing.JTextField();
        tahun_terbit = new javax.swing.JTextField();
        penerbit = new javax.swing.JTextField();
        pengarang = new javax.swing.JTextField();
        jumlah_buku = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledor = new javax.swing.JTable();
        cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        tanggal_beli = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data Buku");

        kode_buku.setBackground(new java.awt.Color(208, 239, 239));
        kode_buku.setForeground(new java.awt.Color(153, 153, 153));
        kode_buku.setText("Kode Buku");
        kode_buku.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kode_bukuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kode_bukuFocusLost(evt);
            }
        });

        judul_buku.setBackground(new java.awt.Color(208, 239, 239));
        judul_buku.setForeground(new java.awt.Color(153, 153, 153));
        judul_buku.setText("Judul Buku");
        judul_buku.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                judul_bukuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                judul_bukuFocusLost(evt);
            }
        });
        judul_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judul_bukuActionPerformed(evt);
            }
        });

        tahun_terbit.setBackground(new java.awt.Color(208, 239, 239));
        tahun_terbit.setForeground(new java.awt.Color(153, 153, 153));
        tahun_terbit.setText("Tahun Terbit");
        tahun_terbit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tahun_terbitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tahun_terbitFocusLost(evt);
            }
        });

        penerbit.setBackground(new java.awt.Color(208, 239, 239));
        penerbit.setForeground(new java.awt.Color(153, 153, 153));
        penerbit.setText("Penerbit");
        penerbit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                penerbitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                penerbitFocusLost(evt);
            }
        });

        pengarang.setBackground(new java.awt.Color(208, 239, 239));
        pengarang.setForeground(new java.awt.Color(153, 153, 153));
        pengarang.setText("Pengarang");
        pengarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pengarangFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pengarangFocusLost(evt);
            }
        });

        jumlah_buku.setBackground(new java.awt.Color(208, 239, 239));
        jumlah_buku.setForeground(new java.awt.Color(153, 153, 153));
        jumlah_buku.setText("Jumlah Buku");
        jumlah_buku.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jumlah_bukuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jumlah_bukuFocusLost(evt);
            }
        });

        tabledor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Buku", "Judul Buku", "Tanggal Beli", "Pengarang", "Penerbit", "Tahun Terbit", "Jumlah Buku "
            }
        ));
        tabledor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledor);

        cari.setForeground(new java.awt.Color(153, 153, 153));

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Keluar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(judul_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kode_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tahun_terbit, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggal_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(penerbit)
                            .addComponent(pengarang)
                            .addComponent(jumlah_buku, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judul_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tahun_terbit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlah_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tanggal_beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void judul_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judul_bukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judul_bukuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kode_bukuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kode_bukuFocusGained
        // TODO add your handling code here:
        if ("Kode Buku".equals(kode_buku.getText())) {
            kode_buku.setText("");
            kode_buku.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_kode_bukuFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            Statement state = handler_class.Koneksi.konek().createStatement();
            String sql = "INSERT INTO buku VALUES ('"+kode_buku.getText()+"','"+judul_buku.getText()+"'"
                    + ",'"+tanggal_beli.getDateFormatString()+"','"+pengarang.getText()+"',"
                    + "'"+penerbit.getText()+"','"+Integer.parseInt(tahun_terbit.getText())+"',"
                    + "'"+Integer.parseInt(jumlah_buku.getText())+"')";
            state.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan");
        }
        loadTable();
        kosong();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void kode_bukuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kode_bukuFocusLost
        // TODO add your handling code here:
        if ("".equals(kode_buku.getText())) {

            kode_buku.setText("Kode Buku");
            kode_buku.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_kode_bukuFocusLost

    private void judul_bukuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_judul_bukuFocusGained
        // TODO add your handling code here:
        if ("Judul Buku".equals(judul_buku.getText())) {
            judul_buku.setText("");
            judul_buku.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_judul_bukuFocusGained

    private void judul_bukuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_judul_bukuFocusLost
        // TODO add your handling code here:
        if ("".equals(judul_buku.getText())) {

            judul_buku.setText("Judul Buku");
            judul_buku.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_judul_bukuFocusLost

    private void tahun_terbitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tahun_terbitFocusGained
        // TODO add your handling code here:
        if ("Tahun Terbit".equals(tahun_terbit.getText())) {
            tahun_terbit.setText("");
            tahun_terbit.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tahun_terbitFocusGained

    private void tahun_terbitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tahun_terbitFocusLost
        // TODO add your handling code here:
        if ("".equals(tahun_terbit.getText())) {

            tahun_terbit.setText("Tahun Terbit");
            tahun_terbit.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_tahun_terbitFocusLost

    private void penerbitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_penerbitFocusGained
        // TODO add your handling code here:
        if ("Penerbit".equals(penerbit.getText())) {
            penerbit.setText("");
            penerbit.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_penerbitFocusGained

    private void penerbitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_penerbitFocusLost
        // TODO add your handling code here:
        if ("".equals(penerbit.getText())) {

            penerbit.setText("Penerbit");
            penerbit.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_penerbitFocusLost

    private void pengarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pengarangFocusGained
        // TODO add your handling code here:
        if ("Pengarang".equals(pengarang.getText())) {
            pengarang.setText("");
            pengarang.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_pengarangFocusGained

    private void pengarangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pengarangFocusLost
        // TODO add your handling code here:
        if ("".equals(pengarang.getText())) {

            pengarang.setText("Pengarang");
            pengarang.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_pengarangFocusLost

    private void jumlah_bukuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jumlah_bukuFocusGained
        // TODO add your handling code here:
        if ("Jumlah Buku".equals(jumlah_buku.getText())) {
            jumlah_buku.setText("");
            jumlah_buku.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_jumlah_bukuFocusGained

    private void jumlah_bukuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jumlah_bukuFocusLost
        // TODO add your handling code here:
        if ("".equals(jumlah_buku.getText())) {

            jumlah_buku.setText("Jumlah Buku");
            jumlah_buku.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jumlah_bukuFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            Statement state = handler_class.Koneksi.konek().createStatement();
            String sql = "delete from buku where kode_buku = '"+kode_buku.getText()+"'";
            state.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Dihapus");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Tidak Dihapus");
        }
        loadTable();
        kosong();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            Statement state = handler_class.Koneksi.konek().createStatement();
            String sql = "update buku set judul_buku='"+judul_buku.getText()+"',"
                    + "tanggal_beli='"+tanggal_beli.getDateFormatString().toString()+"',penerbit='"+penerbit.getText()+"',"
                    + "pengarang='"+pengarang.getText()+"',tahun_terbit='"+Integer.parseInt(tahun_terbit.getText())+"',"
                    + "jumlah_buku='"+Integer.parseInt(jumlah_buku.getText())+"' where kode_buku='"+kode_buku.getText()+"'";
            state.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Di Edit");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Tidak Di Edit");
        }
        loadTable();
        kosong();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new MenuUtamaSuperAdmin().show();
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tabledorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledorMouseClicked
        // TODO add your handling code here:
        int baris = tabledor.rowAtPoint(evt.getPoint());
        String kodebuku = tabledor.getValueAt(baris, 0).toString();
        kode_buku.setText(kodebuku);
        kode_buku.setForeground(new Color(0, 0, 0));
        String jdlbuku = tabledor.getValueAt(baris, 1).toString();
        judul_buku.setText(jdlbuku);
        judul_buku.setForeground(new Color(0, 0, 0));
        String tgl_beli = tabledor.getValueAt(baris, 2).toString();
        tanggal_beli.setDateFormatString(tgl_beli);
        tanggal_beli.setForeground(new Color(0, 0, 0));
        String penerbitt = tabledor.getValueAt(baris, 3).toString();
        penerbit.setText(penerbitt);
        penerbit.setForeground(new Color(0, 0, 0));
        String pengaraang = tabledor.getValueAt(baris, 4).toString();
        pengarang.setText(pengaraang);
        pengarang.setForeground(new Color(0, 0, 0));
        String thn_ternit = tabledor.getValueAt(baris, 5).toString();
        tahun_terbit.setText(thn_ternit);
        tahun_terbit.setForeground(new Color(0, 0, 0));
        String jmlh = tabledor.getValueAt(baris, 6).toString();
        jumlah_buku.setText(jmlh);
        jumlah_buku.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_tabledorMouseClicked

    private void tanggal_beliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tanggal_beliFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal_beliFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judul_buku;
    private javax.swing.JTextField jumlah_buku;
    private javax.swing.JTextField kode_buku;
    private javax.swing.JTextField penerbit;
    private javax.swing.JTextField pengarang;
    private javax.swing.JTable tabledor;
    private javax.swing.JTextField tahun_terbit;
    private com.toedter.calendar.JDateChooser tanggal_beli;
    // End of variables declaration//GEN-END:variables
}
