/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu_superadmin;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luthf
 */
public class Buku extends javax.swing.JFrame {
    
    String nilaiTanggal;

    /**
     * Creates new form LogIn
     */
    public Buku() {
        initComponents();
        loadTable();
    }
    
     private void tanggal() {
        Date date = tanggal_beli.getDate();

        if (date != null) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Format "tahun-bulan-tanggal"
            nilaiTanggal = dateFormat.format(date);
            System.out.println(nilaiTanggal);
        } else {
            nilaiTanggal = "0000-00-00";
        }

    }
    
    private void cariin() {
        Object[]baris={"Kode Buku","Judul Buku","Tanggal Beli","Pengarang","Penerbit","Tahun Terbit","Jumlah Buku"};
        DefaultTableModel tablek = new DefaultTableModel(null, baris);
        tabledor.setModel(tablek);
        String carii = cari.getText();
        
        try{
            Statement state=handler_class.Koneksi.konek().createStatement();
            String sql = "select * from buku WHERE kode_buku LIKE '%"+carii+"%'OR judul_buku LIKE '"+carii+"'" ;
            ResultSet cari = state.executeQuery(sql);
            
            while (cari.next()){
            String a = cari.getString(1);
            String b = cari.getString(2);
            String c = cari.getString(3);
            String d = cari.getString(4);
            String e = cari.getString(5);
            String f = cari.getString(6);
            String g = cari.getString(7);
            Object[]data={a,b,c,d,e,f,g};
            tablek.addRow(data);
        }
    }catch (Exception e){
        System.out.println("Data Gak ada!");
    }
    }
    
    protected void loadTable() {
        Object[]baris={"Kode Buku","Judul Buku","Tanggal Beli","Pengarang","Penerbit","Tahun Terbit","Jumlah Buku"};
        DefaultTableModel tablek = new DefaultTableModel(null, baris);
        tabledor.setModel(tablek);
        
        try{
            Statement state=handler_class.Koneksi.konek().createStatement();
            String sql = "select * from buku ";
            ResultSet cari = state.executeQuery(sql);
            
            while (cari.next()){
            String a = cari.getString(1);
            String b = cari.getString(2);
            String c = cari.getString(3);
            String d = cari.getString(4);
            String e = cari.getString(5);
            String f = cari.getString(6);
            String g = cari.getString(7);
            Object[]data={a,b,c,d,e,f,g};
            tablek.addRow(data);
        }
    }catch (Exception e){
    }
    }
    
    private void kosong(){

        kodeBuku.setText("Kode Buku");
        kodeBuku.setForeground(new Color(153, 153, 153));
        judulBuku.setText("Judul Buku");
        judulBuku.setForeground(new Color(153, 153, 153));
        tanggal_beli.setForeground(new Color(0, 0, 0));
        pengarang.setText("Pengarang");
        pengarang.setForeground(new Color(153, 153, 153));
        penerbit.setText("Penerbit");
        penerbit.setForeground(new Color(153, 153, 153));
        tahunTerbit.setText("Tahun Terbit");
        tahunTerbit.setForeground(new Color(153, 153, 153));
        jumlahBuku.setText("Jumlah Buku");
        jumlahBuku.setForeground(new Color(153, 153, 153));
        cari.setText("");
        loadTable();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kodeBuku = new javax.swing.JTextField();
        judulBuku = new javax.swing.JTextField();
        tahunTerbit = new javax.swing.JTextField();
        penerbit = new javax.swing.JTextField();
        pengarang = new javax.swing.JTextField();
        jumlahBuku = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledor = new javax.swing.JTable();
        cari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBersih = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tanggal_beli = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data Buku");

        kodeBuku.setBackground(new java.awt.Color(208, 239, 239));
        kodeBuku.setForeground(new java.awt.Color(153, 153, 153));
        kodeBuku.setText("Kode Buku");
        kodeBuku.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kodeBukuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kodeBukuFocusLost(evt);
            }
        });

        judulBuku.setBackground(new java.awt.Color(208, 239, 239));
        judulBuku.setForeground(new java.awt.Color(153, 153, 153));
        judulBuku.setText("Judul Buku");
        judulBuku.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                judulBukuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                judulBukuFocusLost(evt);
            }
        });
        judulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulBukuActionPerformed(evt);
            }
        });

        tahunTerbit.setBackground(new java.awt.Color(208, 239, 239));
        tahunTerbit.setForeground(new java.awt.Color(153, 153, 153));
        tahunTerbit.setText("Tahun Terbit");
        tahunTerbit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tahunTerbitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tahunTerbitFocusLost(evt);
            }
        });

        penerbit.setBackground(new java.awt.Color(208, 239, 239));
        penerbit.setForeground(new java.awt.Color(153, 153, 153));
        penerbit.setText("Penerbit");
        penerbit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                penerbitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                penerbitFocusLost(evt);
            }
        });

        pengarang.setBackground(new java.awt.Color(208, 239, 239));
        pengarang.setForeground(new java.awt.Color(153, 153, 153));
        pengarang.setText("Pengarang");
        pengarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pengarangFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pengarangFocusLost(evt);
            }
        });

        jumlahBuku.setBackground(new java.awt.Color(208, 239, 239));
        jumlahBuku.setForeground(new java.awt.Color(153, 153, 153));
        jumlahBuku.setText("Jumlah Buku");
        jumlahBuku.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jumlahBukuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jumlahBukuFocusLost(evt);
            }
        });

        tabledor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Buku", "Judul Buku", "Tanggal Beli", "Pengarang", "Penerbit", "Tahun Terbit", "Jumlah Buku "
            }
        ));
        tabledor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledor);

        cari.setForeground(new java.awt.Color(153, 153, 153));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(0, 0, 0));
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(0, 0, 0));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 0, 0));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnBersih.setBackground(new java.awt.Color(0, 0, 0));
        btnBersih.setForeground(new java.awt.Color(255, 255, 255));
        btnBersih.setText("Bersihkan Form");
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(0, 0, 0));
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jLabel2.setText("Tanggal Pembelian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btnBersih)
                                .addGap(18, 18, 18)
                                .addComponent(btnKeluar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tanggal_beli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(judulBuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                .addComponent(kodeBuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                .addComponent(tahunTerbit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(penerbit)
                                .addComponent(pengarang)
                                .addComponent(jumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)))
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggal_beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnBersih)
                    .addComponent(btnKeluar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void judulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulBukuActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCariActionPerformed

    private void kodeBukuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kodeBukuFocusGained
        // TODO add your handling code here:
        if ("Kode Buku".equals(kodeBuku.getText())) {
            kodeBuku.setText("");
            kodeBuku.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_kodeBukuFocusGained

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        tanggal();
        System.out.println(tanggal_beli);
        try{
            Statement state = handler_class.Koneksi.konek().createStatement();
            String sql = "INSERT INTO buku VALUES ('"+kodeBuku.getText()+"','"+judulBuku.getText()+"'"
                    + ",'"+nilaiTanggal+"','"+pengarang.getText()+"',"
                    + "'"+penerbit.getText()+"','"+Integer.parseInt(tahunTerbit.getText())+"',"
                    + "'"+Integer.parseInt(jumlahBuku.getText())+"')";
            state.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan"+e.getMessage());
        }
        loadTable();
        kosong();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void kodeBukuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kodeBukuFocusLost
        // TODO add your handling code here:
        if ("".equals(kodeBuku.getText())) {

            kodeBuku.setText("Kode Buku");
            kodeBuku.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_kodeBukuFocusLost

    private void judulBukuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_judulBukuFocusGained
        // TODO add your handling code here:
        if ("Judul Buku".equals(judulBuku.getText())) {
            judulBuku.setText("");
            judulBuku.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_judulBukuFocusGained

    private void judulBukuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_judulBukuFocusLost
        // TODO add your handling code here:
        if ("".equals(judulBuku.getText())) {

            judulBuku.setText("Judul Buku");
            judulBuku.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_judulBukuFocusLost

    private void tahunTerbitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tahunTerbitFocusGained
        // TODO add your handling code here:
        if ("Tahun Terbit".equals(tahunTerbit.getText())) {
            tahunTerbit.setText("");
            tahunTerbit.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tahunTerbitFocusGained

    private void tahunTerbitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tahunTerbitFocusLost
        // TODO add your handling code here:
        if ("".equals(tahunTerbit.getText())) {

            tahunTerbit.setText("Tahun Terbit");
            tahunTerbit.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_tahunTerbitFocusLost

    private void penerbitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_penerbitFocusGained
        // TODO add your handling code here:
        if ("Penerbit".equals(penerbit.getText())) {
            penerbit.setText("");
            penerbit.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_penerbitFocusGained

    private void penerbitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_penerbitFocusLost
        // TODO add your handling code here:
        if ("".equals(penerbit.getText())) {

            penerbit.setText("Penerbit");
            penerbit.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_penerbitFocusLost

    private void pengarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pengarangFocusGained
        // TODO add your handling code here:
        if ("Pengarang".equals(pengarang.getText())) {
            pengarang.setText("");
            pengarang.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_pengarangFocusGained

    private void pengarangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pengarangFocusLost
        // TODO add your handling code here:
        if ("".equals(pengarang.getText())) {

            pengarang.setText("Pengarang");
            pengarang.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_pengarangFocusLost

    private void jumlahBukuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jumlahBukuFocusGained
        // TODO add your handling code here:
        if ("Jumlah Buku".equals(jumlahBuku.getText())) {
            jumlahBuku.setText("");
            jumlahBuku.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_jumlahBukuFocusGained

    private void jumlahBukuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jumlahBukuFocusLost
        // TODO add your handling code here:
        if ("".equals(jumlahBuku.getText())) {

            jumlahBuku.setText("Jumlah Buku");
            jumlahBuku.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jumlahBukuFocusLost

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try{
            Statement state = handler_class.Koneksi.konek().createStatement();
            String sql = "delete from buku where kode_buku = '"+kodeBuku.getText()+"'";
            state.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Dihapus");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Tidak Dihapus");
        }
        loadTable();
        kosong();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        tanggal();
        System.out.println(nilaiTanggal);
        try{
            Statement state = handler_class.Koneksi.konek().createStatement();
            String sql = "update buku set judul_buku='"+judulBuku.getText()+"',"
                    + "tanggal_beli='"+nilaiTanggal+"',penerbit='"+penerbit.getText()+"',"
                    + "pengarang='"+pengarang.getText()+"',tahun_terbit='"+Integer.parseInt(tahunTerbit.getText())+"',"
                    + "jumlah_buku='"+Integer.parseInt(jumlahBuku.getText())+"' where kode_buku='"+kodeBuku.getText()+"'";
            state.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Di Edit");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Tidak Di Edit"+e.getMessage());
        }
        loadTable();
        kosong();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btnBersihActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        new MenuUtamaSuperAdmin().show();
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tabledorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledorMouseClicked
        // TODO add your handling code here:
        int baris = tabledor.rowAtPoint(evt.getPoint());
        String kodebuku = tabledor.getValueAt(baris, 0).toString();
        kodeBuku.setText(kodebuku);
        kodeBuku.setForeground(new Color(0, 0, 0));
        String jdlbuku = tabledor.getValueAt(baris, 1).toString();
        judulBuku.setText(jdlbuku);
        judulBuku.setForeground(new Color(0, 0, 0));
        String tgl_beli = tabledor.getValueAt(baris, 2).toString();
        tanggal_beli.setDateFormatString(tgl_beli);
        tanggal_beli.setForeground(new Color(0, 0, 0));
        String penerbitt = tabledor.getValueAt(baris, 3).toString();
        penerbit.setText(penerbitt);
        penerbit.setForeground(new Color(0, 0, 0));
        String pengaraang = tabledor.getValueAt(baris, 4).toString();
        pengarang.setText(pengaraang);
        pengarang.setForeground(new Color(0, 0, 0));
        String thn_ternit = tabledor.getValueAt(baris, 5).toString();
        tahunTerbit.setText(thn_ternit);
        tahunTerbit.setForeground(new Color(0, 0, 0));
        String jmlh = tabledor.getValueAt(baris, 6).toString();
        jumlahBuku.setText(jmlh);
        jumlahBuku.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_tabledorMouseClicked

    private void tanggal_beliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tanggal_beliFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal_beliFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextField cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judulBuku;
    private javax.swing.JTextField jumlahBuku;
    private javax.swing.JTextField kodeBuku;
    private javax.swing.JTextField penerbit;
    private javax.swing.JTextField pengarang;
    private javax.swing.JTable tabledor;
    private javax.swing.JTextField tahunTerbit;
    private com.toedter.calendar.JDateChooser tanggal_beli;
    // End of variables declaration//GEN-END:variables
}
