/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_main;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import menu_superadmin.MenuUtamaSuperAdmin;


/**
 *
 * @author SEKDES
 */
public class laporan extends javax.swing.JFrame {

    /**
     * Creates new form laporan
     */
    public laporan() {
        initComponents();
        cbniss();
    }

    private void cbniss() {
    harian.removeAllItems();
    harian.addItem("~Pilih~");

    try {
        Set<String> uniqueDates = new HashSet<>(); // Set untuk menyimpan tanggal unik

        String Sql = "SELECT * FROM peminjaman";
        Statement st = handler_class.Koneksi.konek().createStatement();
        ResultSet pinjam = st.executeQuery(Sql);

        while (pinjam.next()) {
            String tanggalPinjam = pinjam.getString("tanggal_pinjam");

            // Cek apakah tanggal sudah ada dalam Set
            if (!uniqueDates.contains(tanggalPinjam)) {
                uniqueDates.add(tanggalPinjam); // Tambahkan tanggal ke Set
                harian.addItem(tanggalPinjam); // Tambahkan tanggal ke ComboBox
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Menampilkan Data\n" + e.getMessage());
    }
}


private void struk() {
    PrintJob p = getToolkit().getPrintJob(this, "Cetak Tiket", null);
    Graphics g = p.getGraphics();
    g.setFont(new Font("Serif", Font.BOLD, 20));
    g.drawString("PERPUSTAKAAN SMAN 2 POCHINOK", 35, 22);
    g.drawLine(10, 30, 600, 30);

    try {
        // Ambil data dari database berdasarkan tanggal pinjam yang dipilih
        String tanggalPinjamTerpilih = (String) harian.getSelectedItem();
        String sql = "SELECT * FROM peminjaman WHERE tanggal_pinjam = '" + tanggalPinjamTerpilih + "'";
        Statement st = handler_class.Koneksi.konek().createStatement();
        ResultSet rs = st.executeQuery(sql);

        int y = 50; // Posisi awal Y

        // Tampilkan data pada struk
        while (rs.next()) {
            g.setFont(new Font("Courier New", Font.PLAIN, 12));

            // Tampilkan data dengan penambahan pada posisi Y
            g.drawString("Kode Peminjaman : " + rs.getString("kode_peminjaman"), 10, y);
            g.drawString("Tanggal Pinjam  : " + rs.getString("tanggal_pinjam"), 10, y + 20);
            g.drawString("NIS             : " + rs.getString("nis"), 10, y + 40);
            g.drawString("Nama            : " + rs.getString("nama"), 10, y + 60);
            g.drawString("Kelas           : " + rs.getString("kelas"), 10, y + 80);
            g.drawString("Kode Buku       : " + rs.getString("kode_buku"), 10, y + 100);
            g.drawString("Judul Buku      : " + rs.getString("judul_buku"), 10, y + 120);
            g.drawString("Jumlah Buku     : " + rs.getString("jumlah_buku"), 10, y + 140);
            g.drawString("ID Petugas      : " + rs.getString("id_petugas"), 10, y + 160);

            // Tambahkan garis pemisah antar data
            g.drawLine(10, y + 180, 600, y + 180);

            // Tingkatkan nilai Y untuk baris berikutnya
            y += 200;
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

    p.end();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        harian = new javax.swing.JComboBox<>();
        btnCetak = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        harian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harianActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        jLabel2.setText("Cetak Harian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(harian, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnCetak)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(harian)
                    .addComponent(btnCetak))
                .addGap(129, 129, 129))
        );

        jMenu3.setText("Kembali");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked

        String userLevel = LoginPanel.userLevel;
        System.out.println(userLevel);
        if("superadmin".equals(userLevel)){
            new MenuUtamaSuperAdmin().show();
            dispose();
        }else{
        new MenuUtama().show();
        dispose();
        }
    }//GEN-LAST:event_jMenu3MouseClicked

    private void harianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harianActionPerformed
        try {
            String Sql = "select * from peminjaman where tanggal_pinjam='" + harian.getSelectedItem() + "'";
            Statement state = handler_class.Koneksi.konek().createStatement();
            ResultSet pinjam = state.executeQuery(Sql);
            while (pinjam.next()) {
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_harianActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        struk();
    }//GEN-LAST:event_btnCetakActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JComboBox<String> harian;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
